#!/usr/bin/perl
#===============================================================================
#
#         FILE: portscanner.pl
#
#        USAGE: ./portscanner.pl  
#
#  DESCRIPTION: 
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: Derrick Cope (), derrick(at)thecopes(dot)me
# ORGANIZATION: 
#      VERSION: 1.0
#      CREATED: 08/11/2016 08:43:45 PM
#     REVISION: ---
#===============================================================================

use strict;
use warnings;
use utf8;
use 5.014;

use Socket;

$| = 1;

my ( $ip, $protocol, $port, $myhouse, $yourhouse, $log, $port_stop );

$protocol = getprotobyname('tcp');

($ip, $port, $port_stop, $log) = @ARGV;

if ($ip eq "-h") {
    &usage();
}

$ip =  "localhost" if not $ip;
$port = 1 if not $port;
$port_stop = 65535 if not $port_stop;
$log = "qsopenports.txt" if not $log;

unless (open(LOG_FILE, ">>$log")) {
    die "Can't open log file $log for writing: $!\n"
}

# Make file handle hot so the buffer is flushed after every write
select((select(LOG_FILE), $| = 1)[0]);

print LOG_FILE "The following ports are open on the $ip between port $port and $port_stop\n\n";

print "Checking $ip for open ports..\n";

for (; $port < $port_stop; $port += 1) {
    socket(SOCKET, PF_INET, SOCK_STREAM, $protocol);

    $yourhouse = inet_aton($ip);
    
    $myhouse = sockaddr_in($port, $yourhouse);

    if  (!connect(SOCKET, $myhouse)) {
        printf "%d\r", $port;
    } else {
        printf "%d <- open\n", $port;
        print LOG_FILE "$port\n";
        close SOCKET || die "close: $!";
    }
}

close LOG_FILE || die "$!";
printf "NullBytePortScan complete.\n";
printf "Those are the open ports for: $ip\n";

sub usage() {
    print "Usage: ./nullbyteportscanner [host] [start port] [stop port] [logfile]\n";
    print "Defaults to localhost and port 1 and port 65535
    qsopenports.txt\n";
    exit 0;
}
