#!/usr/bin/perl

#use utf8;

print "barney " x 3;

$barney = 3;

print $barney;

print "$barney x 3";

$fred = 'hello';
print "The name in \$fred.\n";

print "The name in ${fred}s" . "and" . "barney\n";

#$star = \x{F005};

print "\x{F005}\n";

print "孔\n";
